apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: makisu
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: CONTEXTPATH
    description: Path to the build context.
    default: /workspace
  - name: PUSH_REGISTRY
    description: Registry to push image to.
    default: index.docker.io
  # ToDo currently not possible see: https://github.com/knative/build/pull/550
  - name: REGISTRY_SECRET
    description: Secret containing information about the used regsitry.
    default: docker-registry-config
  steps:
  - name: build-and-push
    image: gcr.io/makisu-project/makisu:v0.1.8
    args:
      - build
      - --push=${PUSHREGISTRY}
      - --modifyfs=true
      - --tag=${IMAGE}
      - --registry-config=/registry-config/registry.yaml
      - ${CONTEXTPATH}
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    volumeMounts:
    - name: registry-config
      mountPath: /registry-config
  volumes:
  - name: registry-config
    secret:
      # ToDo currently not possible ${REGISTRY_SECRET}
      secretName: docker-registry-config
